#!/bin/sh 

INTERMEDIATE_SUBJECT=${INTERMEDIATE_SUBJECT:-"/C=SE/ST=Vastra Gotaland/L=Gothenburg/O=MyTest/CN=intermediate.test/"}
export INTERMEDIATE_SUBJECT
CRL_DISTRIBUTION_POINTS=${CRL_DISTRIBUTION_POINTS:-"http://${SERVER_NAME}.crl.pem"}
export CRL_DISTRIBUTION_POINTS
ROOT_KEY_PASSWORD=${ROOT_KEY_PASSWORD:-"Abcd1234"}
export ROOT_KEY_PASSWORD
INTERMEDIATE_KEY_PASSWORD=${INTERMEDIATE_KEY_PASSWORD:-"Abcd1234"}
export INTERMEDIATE_KEY_PASSWORD
SERVER_KEY_PASSWORD=${SERVER_KEY_PASSWORD:-"Abcd1234"}
export SERVER_KEY_PASSWORD
DEFAULT_CRL_DAYS=${DEFAULT_CRL_DAYS:-"1"}
export DEFAULT_CRL_DAYS
DEFAULT_DAYS=${DEFAULT_DAYS:-"1"}
export DEFAULT_DAYS
SERVER_CERT_EXPIRATION_DAYS=:${SERVER_CERT_EXPIRATION_DAYS:-"1"}
export SERVER_CERT_EXPIRATION_DAYS
INTERMEDIATE_CERT_EXPIRATION_DAYS=:${INTERMEDIATE_CERT_EXPIRATION_DAYS:-"1"}
export INTERMEDIATE_CERT_EXPIRATION_DAYS
ROOT_CERT_EXPIRATION_DAYS=:${ROOT_CERT_EXPIRATION_DAYS:-"1"}
export ROOT_CERT_EXPIRATION_DAYS

/usr/local/bin/confd -onetime -backend env
/usr/local/bin/create.certificates.sh
