#!/bin/sh 

SERVER_NAME=${SERVER_NAME:-"ci.test"}
ROOT_SUBJECT=${ROOT_SUBJECT:-"/C=SE/ST=Vastra Gotaland/L=Gothenburg/O=MyTest/CN=root.test/"}
INTERMEDIATE_SUBJECT=${INTERMEDIATE_SUBJECT:-"/C=SE/ST=Vastra Gotaland/L=Gothenburg/O=MyTest/CN=intermediate.test/"}
SERVER_SUBJECT=${SERVER_SUBJECT:-"/C=SE/ST=Vastra Gotaland/L=Gothenburg/O=MyTest/CN=${SERVER_NAME}/"}
CRL_DISTRIBUTION_POINTS=${CRL_DISTRIBUTION_POINTS:-"http://${SERVER_NAME}.crl.pem"}
ROOT_KEY_PASSWORD=${ROOT_KEY_PASSWORD:-"Abcd1234"}
INTERMEDIATE_KEY_PASSWORD=${INTERMEDIATE_KEY_PASSWORD:-"Abcd1234"}
SERVER_KEY_PASSWORD=${SERVER_KEY_PASSWORD:-"Abcd1234"}
DEFAULT_CRL_DAYS=${DEFAULT_CRL_DAYS:-"1"}
DEFAULT_DAYS=${DEFAULT_DAYS:-"1"}
SERVER_CERT_EXPIRATION_DAYS=:${SERVER_CERT_EXPIRATION_DAYS:-"1"}
INTERMEDIATE_CERT_EXPIRATION_DAYS=:${INTERMEDIATE_CERT_EXPIRATION_DAYS:-"1"}
ROOT_CERT_EXPIRATION_DAYS=:${ROOT_CERT_EXPIRATION_DAYS:-"1"}

/usr/local/bin/confd -onetime -backend env
/usr/local/bin/create.certificates.sh
